### PR TITLE
Bicep net

### PR DESCRIPTION
**Pull request by SimonWahlin**
Draft for using BicepNet.PS instead of Bicep dlls

    To make this work we need to copy BicepNet.PS folder into the sources folder.
    BicepNet.PS can be found at PSBicep/BicepNet
    Run scripts/build.ps1 to build the module into
    out-folder and copy this this project.

    TODO:
    - Fix Test-BicepFile
    - Set up scripts to download BicepNet.PS
    - Create workflow to publish BicepNet.PS as release

### CODE REVIEW

**Comment by StefanIvemo** [comment]
Done some quick tests and it looks great! 

Bumped into an issue with `ConvertTo-Bicep`. Will do some more testing tomorrow.

```powershell
ConvertTo-Bicep -Path c:\git\StefanIvemo\BicepPowerShell\tmp\sub.json
WARNING: Decompilation is a best-effort process, as there is no guaranteed mapping from ARM JSON to Bicep.
You may need to fix warnings and errors in the generated bicep file(s), or decompilation may fail entirely if an accurate conversion is not possible.       
If you would like to report any issues or inaccurate conversions, please see https://github.com/Azure/bicep/issues.
ConvertTo-BicepNetFile: C:\git\StefanIvemo\BicepPowerShell\Source\Public\ConvertTo-Bicep.ps1:29:61
Line |
  29 |  …            $BicepObject = ConvertTo-BicepNetFile -Path $file.FullName
     |                                                           ~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try
     | the command again.

No bicep files located in path
```

**Comment by SimonWahlin** [comment]
ConvertTo-Bicep should be working now.

**Comment by StefanIvemo** [comment]
Done a lot of additional testing and I can't find any issues. Is there anything left to do?

**Comment by SimonWahlin** [comment]
Need to fix the cache task in the pipeline, then I think we are ready.

**Comment by StefanIvemo** [comment]
Great! We need to make a game plan then. 🙂

**Comment by SimonWahlin** [comment]
We can merge this into the Version2.0 branch and potentially create a prerelease/preview version to unblock the ones stuck on assembly conflicts.

**Comment by StefanIvemo** [comment]
Sounds great! Will look into how to publish a prerelease tonight.

**Review by StefanIvemo — APPROVED** [review]

**Comment by StefanIvemo** [comment]
ConvertTo-Bicep throws this error when I test on my Ubuntu WSL.

```powershell
PS /mnt/c/git/stefanivemo/biceppowershell/source> ConvertTo-Bicep C:\git\StefanIvemo\BicepPowerShell\Source\azureFirewalls.json
WARNING: Decompilation is a best-effort process, as there is no guaranteed mapping from ARM JSON to Bicep.
You may need to fix warnings and errors in the generated bicep file(s), or decompilation may fail entirely if an accurate conversion is not possible.
If you would like to report any issues or inaccurate conversions, please see https://github.com/Azure/bicep/issues.
Get-ChildItem: /mnt/c/git/stefanivemo/biceppowershell/source/Public/ConvertTo-Bicep.ps1:26
Line |
  26 |  …     $files = Get-Childitem -Path $Path -Filter '*.json' -File | Selec …
     |                                                            ~~~~~
     | A parameter cannot be found that matches parameter name 'File'.
```

**Review by StefanIvemo — APPROVED** [review]

**Pull request merged**
