### PR TITLE
Added Get-BicepApiReference

### LINKED ISSUE #26: New cmdlet to fetch API reference docs - Get-BicepApiReference
**Is your feature request related to a problem? Please describe.**
When authoring templates you often find your self navigating to the API specification in the browser to look up properties. We should have a cmdlet that finds the docs for you and opens it in a browser.

**Describe the solution you'd like**
Implement a command called `Get-BicepApiReference` that opens the API reference in a browser. 

**Get the API reference for a resource defined in a template**
Lets say you have a template `vnet.bicep` file that contains a resource named `MyVNet`. 
```
resource MyVNet 'Microsoft.Network/virtualNetworks@2020-06-01' = {
  name: vnetName
  location: 'westeurope'
  properties: {
    addressSpace: {
      addressPrefixes: addressPrefixes
    }
  }
}
```

To get the API Reference for the resource `MyVnet` in the template (`Microsoft.Network/virtualNetworks` API Version `2020-06-01` ). The following command should work.

`Get-BicepApiReference -TemplateFile "/vnet.bicep" -Resource "MyVNet"`

**Get API reference for a resource not defined in a template**
You should also be able to manually specify a resource provider, resource and API Version using the following parameters.

`Get-BicepApiReference -ResourceProvider "Microsoft.Network" -Resource "virtualNetworks"`

Or using the `-ApiVersion` parameter to get a specific API Version.

`Get-BicepApiReference -ResourceProvider "Microsoft.Network" -Resource "virtualNetworks" -ApiVersion "2020-04-01"`

**Additional context**

### PR DESCRIPTION
**Pull request by JohnRoos**
Added public function Get-BicepApiReference and private function GetBicepTypes.

To get parameter completion to work, I also changed downloadAssemblies.ps1 to download the json file containing all the types we need.
In Bicep.psm1 I added one line where we load th types during module import to have the ready for argument completer.

I could only get the argument completer to work with global variables, which I dont like, so we might want to look into that in the future (or if someone has a solution for that right away).

### Get-BicepApiReference
Get-BicepApiReference opens a browser with the official documentation about the ARM template API reference.

#### Syntax
Get-BicepApiReference can be used in two ways:

`Get-BicepApiReference -ResourceProvider Microsoft.Aad -Resource domainServices -ApiVersion 2017-01-01`
All the parameters support auto-completion. ApiVersion is optional. Latest will be used if omitted.

`Get-BicepApiReference -Type 'Microsoft.Aad/domainServices@2017-01-01'`
This makes it easy to just copy-paste from a bicep file.

Documentation and tests are still needed.

Closes #26

### CODE REVIEW

**Comment by StefanIvemo** [comment]
Really like this! Looks and works awesome! Realized one thing though while testing. Maybe we should add one more parameter called `-Child`. A lot of Azure services have child resources, and you should be able to get to them directly like this:

`Get-BicepApiReference -ResourceProvider Microsoft.ApiManagement -Resource service -Child  certificates`
or
`Get-BicepApiReference -Type 'Microsoft.ApiManagement/service/certificates@2019-12-01'`

At the moment it still works if I send in `-Type 'Microsoft.ApiManagement/service/certificates@2019-12-01'` it will just get me to the API spec for `Microsoft.ApiManagement/service` instead of  `Microsoft.ApiManagement/service/certificates` .

Not sure if it's worth it though, you can easily navigate to the child resource from the parent in the docs.

**Comment by StefanIvemo** [comment]
Is it also possible to change the sort order for the API version? If I write `-APIVersion` and press tab I want it to start with the latest and list the versions in falling order.

**Comment by JohnRoos** [comment]
> Really like this! Looks and works awesome! Realized one thing though while testing. Maybe we should add one more parameter called `-Child`. A lot of Azure services have child resources, and you should be able to get to them directly like this:
> 
> `Get-BicepApiReference -ResourceProvider Microsoft.ApiManagement -Resource service -Child certificates`
> or
> `Get-BicepApiReference -Type 'Microsoft.ApiManagement/service/certificates@2019-12-01'`
> 
> At the moment it still works if I send in `-Type 'Microsoft.ApiManagement/service/certificates@2019-12-01'` it will just get me to the API spec for `Microsoft.ApiManagement/service` instead of `Microsoft.ApiManagement/service/certificates` .
> 
> Not sure if it's worth it though, you can easily navigate to the child resource from the parent in the docs.

It wouldnt hurt to add child as well. It can be an optional parameter. I will add it as soon as I have time.

**Comment by JohnRoos** [comment]
Both changes added. Hopefully I didn't break anything :)

**Comment by StefanIvemo** [comment]
Works awesome! But I just have to throw a curve ball at you. Can I get auto-complete on `-Types` as well 😊.  The data is in the JSON and what harm can a couple of more lines of parameter validation do?

bicep-types

**Comment by JohnRoos** [comment]
Yes, we can do that. Its a great idea. I will get to it :)

**Comment by StefanIvemo** [comment]
Just writing this down while it's in my head. The `BicepTypes.json` file needs to be updated regularly and it is something that we can make sure is updated by our build pipelines when we create a new release. But it will be updated more frequent than we will release new versions. Maybe we should create a `Update-BicepTypes` cmdlet that fetches the latest types info and updates the `BicepTypes.json` in the assets folder.

**Comment by JohnRoos** [comment]
That's a good idea. While we download the file we could strip it down to the bare minimum that we need. That would make the module smaller and it would import faster with less logic.

**Comment by StefanIvemo** [comment]
I will create a new issue for `Update-BicepTypes` then.

**Comment by JohnRoos** [comment]
Argument completer for Type has been added.

**Comment by JohnRoos** [comment]
Using classes instead, which makes the completer a bit nicer to use as well as fixing the global variable issue. Tooltip shows the complete type while pressing Ctrl+space.

**Review by StefanIvemo — APPROVED** [review]
This is awesome! Great job!

**Pull request merged**
