### PR TITLE
Added try/catch to hide error msg

### PR DESCRIPTION
**Pull request by emilguden**
Added try/catch to hide error msg.
I bet it can be done much nicer, any feedback is appreciated!

### CODE REVIEW

**Comment by StefanIvemo** [comment]
Added a comment in issue #190 with the solution I would like to see. I don't like that we just suppress an error that actually is valid.

**Comment by matsest** [comment]
What about narrowing down the files it loops over, by only considering files that match the [ARM template schemas](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/syntax)? e.g. something like

```powershell
process {
        $jsonFiles = Get-Childitem -Path $Path -Filter '*.json' -File
        $armTemplates = $jsonFiles | Select-String -Pattern "schema.management.azure.com/schemas/.*deploymentTemplate.json#" | Get-ChildItem # this should match all the ARM template schemas
        if ($armTemplates) {
            foreach ($file in $armTemplates) {
            ...
        }
        else {
            Write-Host "No ARM template files located in path $Path" # this should specify ARM templates, rather than Bicep files - right?
        }
```

Of course the filtering could be done more fancy with Convert-ToJson and checking for a schema property.

**Comment by StefanIvemo** [comment]
@matsest thank you for the suggested solution! Waiting in suspense on a new commit from @emilguden.

**Comment by emilguden** [comment]
@matsest - Thanks for the tip, tried to solve it in a similar way, let's see what @StefanIvemo says 😄 🤞🏼

**Comment by StefanIvemo** [comment]
Thanks @emilguden! Will do a review tomorrow. Need the docs and help updated to get merged.

**Comment by StefanIvemo** [comment]
Looks good!

**Review by StefanIvemo — APPROVED** [review]

**Pull request merged**
