### PR TITLE
New command Convert-BicepParamsToDecoratorStyle

### PR DESCRIPTION
**Pull request by StefanIvemo**
Added new command `Convert-BicepParamsToDecoratorStyle` mentioned in #133 

- New command added `Convert-BicepParamsToDecoratorStyle`
- Added an `-IgnoreDiagnostics` switch to `ParseBicep` and `BuildBicep` to support the new command without outputting diagnostics
- Updated help file
- Fixed docs for `Build-Bicep` and created docs for `Convert-BicepParamsToDecoratorStyle`

How it works:

**params.bicep**
```bicep
param location string = resourceGroup().location
param sku string {
  default: 'Premium'
  allowed: [
    'Standard'
    'Premium'
  ]
}
param publicipcount int {
  default: 1
  metadata: {
    description: 'Specifies the number of public IPs to allocate to the firewall when deploying Azure Firewall'
  }
}
param psk string {
   secure: true
}
```
Convert the parameters from input `.bicep` file to decorator style:
```powershell
Convert-BicepParamsToDecoratorStyle -Path .\params.bicep
param location string = resourceGroup().location

@allowed([
  'Standard'
  'Premium'
])
param sku string = 'Premium'

@description('Specifies the number of public IPs to allocate to the firewall when deploying Azure Firewall')
param publicipcount int = 1

@secure()
param psk string
````

or using the `-ToClipboard` switch:
```powershell
Convert-BicepParamsToDecoratorStyle -Path .\params.bicep -ToClipboard
Decorator style params saved to clipboard
```

### CODE REVIEW

**Comment by StefanIvemo** [comment]
@matsest if you want, I'd be happy if you could verify that my `-ToClipboard` switch works on non-windows systems 🙂

**Comment by matsest** [comment]
Awesome @StefanIvemo!

It does not work for me on my Powershell stable version on Linux (Fedora 34, Wayland) with xclip installed.

```pwsh
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.11.17-300.fc34.x86_64 #1 SMP Wed Apr 28 14:21:28 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I can't get the Set-Clipboard command natively to run on it here. Not sure why, will try to find out.

However it does work with Powershell Preview:

```pwsh
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Linux 5.11.17-300.fc34.x86_64 #1 SMP Wed Apr 28 14:21:28 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Will try to test with my Mac and WSL on Windows later and get back to you.

Generally speaking, copying to clipboard on Linux system is not something that is standardized, as compared to Win/Linux. E.g. `xclip` is not a natively installed command on a lot of systems - but it is the command used in Set-Clipboard in Powershell 7.

### Mac
I'm pretty certain the assertion you have for !$isWindows with xclip is too limited. If you look at the implementation of Set-Clipboard you see that it uses `pbcopy` for Mac:

https://github.com/PowerShell/PowerShell/blob/v7.1.3/src/Microsoft.PowerShell.Commands.Management/commands/management/Clipboard.cs (check also other tags for how it looks in preview versions)

**Comment by StefanIvemo** [comment]
@matsest Thanks for testing it! I had some issues with getting `Set-Clipboard` working in my WSL (Ubuntu-20.04), but got it working by updating from PowerShell 7.1.2 to 7.1.3. It didn't really work as I expected though, I could get the data from the clipboard using `Get-Clipboard` but not paste from the clipboard. 

Maybe I should just make the `-ToClipboard` switch a Windows only thing for now and open a new issue to on work cross-platform support separately.

**Review by emilguden — APPROVED** [review]
Looks good!

**Pull request merged**
